### ISSUE TITLE
请问大佬有兴趣一起做 Element 支持 Vue 3.0

### ISSUE THREAD

**Issue by zazzaz** [Const-Team/Element#34]
https://github.com/element-plus/element-plus

偶然发现我们在做差不多的事情，要不要考虑来一起把 Element 做的更好 😁

**Comment by wangdaodao** [comment]
> 
> 
> https://github.com/element-plus/element-plus
> 
> 偶然发现我们在做差不多的事情，要不要考虑来一起把 Element 做的更好 😁

一直在关注，我会参与的。

**Comment by zazzaz** [comment]
期待大佬一起
